export const DATATABLE = [
  "Domain",
  "Sub Domain",
  "Category",
  "Sub Category",
  "Health Outcome",
  "Variable",
  "Variable Name",
  "Variable Description",
  "Sex",
  "Race",
  "Ethnicity",
  "Age",
  "Geography",
  "Data Unit",
  "Data Year",
  "Data Source Name",
  "Data Source (URL)",
  "Data Portal Name",
  "Data Portal (URL)",
  "Data Format",
  "Data Location",
  "Accessed Date",
  "Processed (Y/No)",
  "Note",
]
